### PR TITLE
Fix: build

### PR DESCRIPTION
**Pull request by dblock**

### CODE REVIEW

**Comment by dblock** [comment]
Doesn't look like CI status is picking up automatically today, https://travis-ci.org/github/michaelherold/benchmark-memory/builds/728322337 is green.

**Comment by AlexWayfer** [comment]
Travis CI is pretty bad in our days, you can check https://github.com/tycooon/memery/issues/28 and https://github.com/excpt/moments/issues/3

Cirrus CI looks perfect for me. CircleCI and GitHub Actions are also better. I can make a PR with any of them, but a new CI should be enabled before this CI as GitHub Application.

**Comment by michaelherold** [comment]
Let's do GitHub Actions. It's nice to have everything in one place. Thanks for volunteering, @AlexWayfer.

**Comment by dblock** [comment]
You could just flip the switch for Travis and this PR though. Why wait for @AlexWayfer to migrate?

**Comment by michaelherold** [comment]
Oh, I misread the message earlier. Apologies!

**Pull request merged**
