### PR TITLE
Add EditorConfig file

### PR DESCRIPTION
**Pull request by AlexWayfer**
More info here: https://editorconfig.org/

Also fix some file-end newlines.

### CODE REVIEW

**Comment by michaelherold** [comment]
On open source projects, I prefer not to introduce tool-specific files to the repository. Thanks for the thought, but I'm going to reject this one.

**Comment by AlexWayfer** [comment]
> On open source projects, I prefer not to introduce tool-specific files to the repository. Thanks for the thought, but I'm going to reject this one.

It's a common standard (you can use any tool for it) for preventing errors with whitespaces especially (like a fixed one in this PR).

You already have files for CodeClimate, Git, Hound, RSpec, RuboCop, Travis, YARD, maybe something else, and you're rejecting a more common one. It's weird. 😕

**Comment by michaelherold** [comment]
Thanks for challenging my statement!

All of the tools that you listed are _project_ tools, whereas an EditorConfig file is a _tool_ tool, meaning that it's meant to configure the editor when you're editing the files in the project. It's an excellent tool for that job; we use it in my day job. However, it's primarily useful for cases where you are using non-standard formatting for a language or writing in a language that doesn't have standard formatting, like C. At my day job, for example, we use tabs in our Ruby code for some reason.

Since our listing and testing harness checks for style compatibility _and_ we use standard Ruby formatting in this codebase, the EditorConfig file isn't necessary; its purpose is already covered from two different angles.

**Comment by AlexWayfer** [comment]
> All of the tools that you listed are _project_ tools, whereas an EditorConfig file is a _tool_ tool, meaning that it's meant to configure the editor when you're editing the files in the project.

Sorry, what? Can you describe a difference between these? I can also describe any of that like you:

> EditrorConfig is a _project_ tool (for a project, you know), whereas a RuboCop file is a …

Wait, what? "file is a _tool_ tool"? Are you sure this is correct? OK, I'm going to try to explain without false-quotes examples.

* [EditorConfig](https://editorconfig.org/) is a standard on paper (like language, DSL, syntax). Any plugin for Editor config is a tool for this standard. `.editorconfig` is a config file for these tools (to be honest, this config name even mentioned in the standard itself, so it's more common than examples below).
* [Ruby Style Guide](https://rubystyle.guide/) is a standard on paper. [RuboCop](https://rubocop.org/) as the tool for this standard. `.rubocop.yml` is a config file for the RuboCop (not a standard itself even).
* [YARD](https://yardoc.org/) is not a standard at all, it's a tool. However, this project has its config file.
* The similiar about CI. Is "CI" a standard? Or specs? Specs don't require CI, so…

All of these things (their config files) placed in the project root. So it's project-scoped, project-related, not something else.

Also I've already fixed the error caused by lack of, you can say "somebody's attention", I'd say "this tool". Tools should help people.

And I don't suggest to include some config files for specific OSes (like macOS) or IDEs (like IDEA), I'm suggesting pretty common (general) standard about important things in the project. Which is optional by the way, but can help others to prevent such mistakes like the fixed one.

**Comment by AlexWayfer** [comment]
> Thanks for challenging my statement!

Something about my last statement?… 😰

**Comment by AlexWayfer** [comment]
OK, no more challenging… 😞

**Pull request closed without merging**
